#ifndef SOCKETINTERFACE_H
#define SOCKETINTERFACE_H


// REQUEST command format:
#define CMD_GETMODE "CMD_GETMODE"
#define CMD_SETMODE "CMD_SETMODE"
#define CMD_POLL "CMD_POLL"

//CMD_SETMODE(int)

//RESPONSE COMMAND
#define RET_SUCCESS "RET_SUCCESS"
#define RET_FAILURE "RET_FAILURE"
#define RET_NOCMD "RET_NOCMD"
#define RET_CMD_NOTIFYCHANGE "RET_CMD_NOTIFYCHANGE"



#endif
